### ISSUE TITLE
Lage nve-tabs komponent

### ISSUE THREAD

**Issue by amish1188** [NVE/Designsystem#374]
Vi skal bygge nve-tabs basert på [figma skisser ](https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=111-25&p=f&m=dev).

**Forslag til å bygge en komponent uten Shoelace:**
Fokuser kun på selve visningen av knappene, ikke innholdet i tab-panelet. Grunnen til dette er at det sannsynligvis er mest nyttig om brukerne selv kan bestemme hvordan de vil håndtere visningen av panelene når en tab er aktiv.

Start med radio-group (det er ikke nødvendig å bruke nve-radio-group med mindre man ønsker å eksperimentere med styling eller overskriving). Radio-gruppen sikrer allerede at kun én tab kan være aktiv om gangen. Deretter kan du returnere en change- eller input-hendelse som informerer om hvilken verdi som ble aktivert.

Shoelace bruker [knapper for scrolling](https://shoelace.style/components/tab-group). Vi kan starte enkelt ved kun å vise en scroll-bar under tabbene i stedet. Sørg imidlertid for å style den, slik at den ikke ser uestetisk ut.

**Eksempel på hvordan du kan style scroll-baren:**
```css
.toolbar::-webkit-scrollbar {
  height: 6px;
  pointer-events: auto;
}

.toolbar::-webkit-scrollbar-track {
  background: #f1f1f1;
}

.toolbar::-webkit-scrollbar-thumb {
  background: #c0bfbf;
  border-radius: 6px;
}

/* viser ikke scrollbar på touchscreen */
@media screen and (max-width: mobil bredde) and (pointer: coarse) {
  .toolbar::-webkit-scrollbar {
    display: none;
  }
}
```
